system_prompt_services = """Below is a list of all the relevant medical information of a patient. 
I want you to tell me a list of medical departments that may be relevant to this. 
Order the departments by diseases that are most emergency ones, and also the most likely, limited to 3, one per line.
Do not say anything else"""


list_services = """
'Accident and emergency services',
 'Adult Mental Illness',
 'Aerobics',
 'Alcohol Addiction support',
 'Alcohol addiction - support for family and friends',
 'Alcohol addiction treatment',
 'Alcohol services for homeless people',
 'Alcohol services for minority ethnic groups',
 'Alcohol services for offenders',
 'Allergy services in hospital',
 "Alzheimer's information and support",
 'Ambulance services',
 'Anticoagulant monitoring and dosing - provided in-house',
 'Appliance dispensing (prescription charges apply)',
 'Appliance use review service (NHS)',
 'Appointment booking available for consultations',
 'Appointment booking for consultations not required',
 'Archery',
 'Asthma Clinic',
 'Athletics',
 'Baby clinic with health visitor',
 'Back services',
 'Badminton',
 'Basketball',
 'Beach Volleyball',
 'Boccia',
 'Boxercise',
 'Boxing',
 'Braces and other orthodontic treatment ',
 'Breast Surgery',
 'Breast cancer services',
 'Breast screening services',
 'COPD clinic with spirometry',
 'COVID-19 lateral flow tests (eligible NHS patients)',
 'Cancer Services',
 'Cancer information and support',
 'Cancer support for women',
 'Cardiac services (community)',
 'Cardiology',
 'Cardiothoracic surgery',
 'Care services for people with dementia',
 'Care services for people with eating disorders',
 'Care services for people with learning disabilities',
 'Carer benefits and legal services',
 'Carer centres and services',
 'Carer national organisations',
 'Carer service for BME groups',
 'Carers emotional support services',
 'Carers respite and breaks',
 'Carers travel and transport',
 'Caring for adults over 65',
 'Caring for adults under 65',
 'Caring for children (0 - 18)',
 'Cataract Surgery',
 'Child Immunisations',
 'Child and adolescent mental health services (CAMHS)',
 'Child health and development',
 "Children's & Adolescent Services",
 'Chinese Martial arts and combat',
 'Chlamydia - free online tests for u-25s',
 'Chlamydia screening and treatment (NHS)',
 'Chlamydia screening and treatment (paid-for)',
 'Chlamydia screening under 25s',
 'Chronic Obstructive Pulmonary Disease',
 'Circuits',
 'Cognitive behavioural therapy services',
 'Colorectal cancer services',
 'Community mental health services',
 'Condom supply (NHS)',
 'Consultation services',
 'Contraception information and advice',
 'Counselling for alcohol addiction',
 'Counselling for drug addiction',
 'Counselling services',
 'Cricket',
 'Cycling',
 'Day treatment services',
 'Dementia Services',
 'Dementia information and support',
 'Dental services (community)',
 'Dentistry and Orthodontics',
 'Dermatology',
 'Diabetes Clinic providing insulin initiation',
 'Diabetic Medicine',
 'Diabetic eye screening',
 'Diagnostic Endoscopy',
 'Diagnostic Imaging',
 'Diagnostic Physiological Measurement',
 'Dialysis',
 'Dietetics',
 'Dietician - provided in house and available on NHS',
 'Disability information and support',
 'Dressings clinic (nurse led)',
 'Drug addiction support',
 'Drug and alcohol Services',
 'Drug misuse - support for family and friends',
 'Drug services for HIV',
 'Drug treatment services',
 'Ear, Nose & Throat',
 'Emergency Abdominal Surgery',
 'Emergency contraception',
 'Emergency contraception (NHS)',
 'Emergency contraception (paid-for)',
 'Endocrine and thyroid surgery',
 'Endocrinology and Metabolic Medicine',
 'Eye - accident and emergency services',
 'Flu Clinic',
 'Football',
 'Forensic Psychiatry',
 'Free condoms',
 'GP services',
 'Gastrointestinal and Liver services',
 'General Gym',
 'General Medicine',
 'General Surgery',
 'General sports',
 'Genetics',
 'Geriatric Medicine',
 'Golf',
 'Group Exercise Class',
 'Gym Class Strength',
 'Gym Class Toning',
 'Gymnastics',
 'Gynaecology',
 'HIV advice and advocacy',
 'HIV sexual health services',
 'HIV support',
 'HIV testing ',
 'HIV treatment',
 'Haematology',
 'Handball',
 'Head lice management',
 'Health Check (paid-for)',
 'Health and Fitness',
 'Healthwatch',
 'Healthy start vitamins',
 'Hearing impairment information and support',
 'Hepatitis C information and support',
 'Hockey',
 'Home aids and adaptions',
 'Hormonal injections/implants',
 'Imaging services',
 'Immunology',
 'Indoor Climbing',
 'Infectious Diseases',
 'Inhaler recycling',
 'Inhaler technique service (NHS)',
 'Inhaler technique service (Non-NHS)',
 'Inpatient Diabetes',
 'Intensive Care',
 'Ju Jitsu',
 'Karate',
 'Laser/cosmetic services - not available on NHS',
 'Learning disability health check',
 'Long-Acting Reversible Contraception (LARC - eg IUD or implant)',
 'Lung cancer services',
 'Major trauma',
 'Maternity services',
 'Medication review service',
 'Memory services',
 'Mental Health - Adults of all ages',
 'Mental health conditions',
 'Mental health support for young people',
 'Minor Ailment Service (NHS)',
 'Minor ailment service',
 'Minor surgery (e.g. removal of moles and skin lesions) - provided in-house',
 'Mobile app to manage repeat prescriptions',
 'Movement & Dance',
 'Multi-lingual staff',
 'Multiple sclerosis nurse services',
 'Muscular dystrophy information and support',
 'NHS Blood Pressure Check Service',
 'NHS Health Check',
 'NHS Pharmacy Contraception Service',
 'NHS psychological therapies services (IAPT), including cognitive behavioural therapy (CBT) ',
 'NHS sight tests',
 'Needle and syringe exchange',
 'Neonatal Care',
 'Nephrology',
 'Netball',
 'Neurology',
 'Neurosurgery',
 'New Medicine Service (NHS)',
 'New medicine service',
 'Newborn hearing screening',
 'Obstetrics',
 'Obstetrics And Gynaecology',
 'Occupational therapy services',
 'Oesophago-Gastric cancer surgery',
 'Old Age Psychiatry',
 'Oncology - Clinical',
 'Oncology - Medical',
 'Ophthalmology',
 'Oral and Maxillofacial Surgery',
 'Orthopaedics',
 'Other health professionals onsite',
 'Outdoor Climbing',
 'Outpatient mental health services',
 'Ovarian cancer information and support',
 'Paediatric Surgery',
 'Paediatric intensive care',
 'Pain Management',
 'Parent carers services',
 'Parenting information and support',
 'Patient advice and liaison services (PALS)',
 'People subject to Mental Health Act',
 'Pharmacy Service (NHS): Condom supply',
 'Pharmacy Service (NHS): Emergency contraception',
 'Pharmacy Service (NHS): Gluten-free food service',
 'Pharmacy Service (NHS): Healthy start vitamins',
 'Pharmacy Service (NHS): Inhaler technique service',
 'Pharmacy Service (NHS): Medication review service',
 'Pharmacy Service (NHS): Minor ailment service',
 'Pharmacy Service (NHS): Stop smoking service',
 'Pharmacy Service (NHS): Stop smoking voucher service',
 'Pharmacy Service (NHS): Supervised consumption of medicines',
 'Pharmacy Service (NHS): Vaccination service',
 'Pharmacy Service (Non-NHS): Emergency contraception',
 'Pharmacy Service (Non-NHS): Inhaler technique service',
 'Pharmacy Service (Non-NHS): Seasonal flu vaccination service (not at risk groups)',
 'Pharmacy Service (Non-NHS): Stop smoking service',
 'Pharmacy Service (Non-NHS): Vaccination service',
 'Pharmacy Service:  Internet Pharmacy',
 'Pharmacy Service: Appliance Dispensing',
 'Pharmacy Service: Appliance dispensing',
 'Pharmacy Service: Appointment booking available for consultations',
 'Pharmacy Service: Appointment booking for consultations not required',
 'Pharmacy Service: Collect Lateral Flow Device ',
 'Pharmacy Service: Community Pharmacy',
 'Pharmacy Service: Electronic Prescription Service',
 'Pharmacy Service: Multi-lingual staff',
 'Pharmacy Service: New medicine service',
 'Pharmacy Service: Prescription collection from local General Practices',
 'Pharmacy Service: Prescription delivery service',
 'Pharmacy Service: Private consultation room',
 'Pharmacy Service: Public Health',
 'Pharmacy Service: Seasonal flu vaccination service (at risk groups)',
 'Pharmacy available on-site',
 'Pharmacy services',
 'Phlebotomy',
 'Physical disabilities',
 'Physiotherapy',
 'Physiotherapy - provided in house and available on NHS',
 'Pilates',
 'Plastic surgery',
 'Podiatrists and chiropodists',
 'Podiatry',
 'Podiatry services (community)',
 'Pregnancy termination',
 'Pregnancy testing',
 'Pregnancy testing (NHS)',
 'Pregnancy testing (paid-for)',
 'Prescription collection from local General Practices',
 'Prescription delivery service',
 'Primary care counselling service',
 'Private consultation room',
 'Prostate Cancer Service',
 'Psychiatric intensive care unit',
 'Psychiatry services',
 'Rape and sexual assault referral centres',
 'Reflexology services',
 'Rehabilitation care services',
 'Relationship counselling',
 'Respiratory Medicine',
 'Rheumatology',
 'Rugby Union',
 'SMS repeat prescription reminders',
 'STI testing and treatment',
 'Seasonal flu vaccination service (at risk groups)',
 'Seasonal flu vaccination service (not at risk groups)',
 'Seasonal flu vaccination service: at-risk groups (NHS)',
 'Seasonal flu vaccination service: not at-risk groups (paid-for)',
 'Sensory impairments',
 'Sexual health information and support',
 'Sexual health services',
 'Sexual health services for young people',
 'Sleep Medicine',
 'Smoking cessation clinic',
 'Softball',
 'Speech and language services',
 'Sports and Exercise Medicine',
 'Sports and Fitness',
 'Squash',
 'Stoma appliance customisation service (NHS)',
 'Stop smoking service (NHS)',
 'Stop smoking service (paid-for)',
 'Stop smoking support services',
 'Stop smoking voucher service',
 'Stop smoking voucher service (NHS)',
 'Stroke',
 'Substance misuse problems',
 'Supervised consumption of medicines',
 'Surgery - include more complex procedures to take teeth out (oral surgery)',
 'Swimming',
 'Table tennis',
 'Taekwondo',
 'Tennis',
 'Therapy services',
 'Trauma services',
 'Travel clinic (paid for)',
 'Travel health with yellow fever',
 'Travel health without yellow fever',
 'Type 2 diabetes screening (NHS)',
 'Unplanned pregnancy information and support',
 'Urgent care centre',
 'Urology',
 'Vaccination service (NHS)',
 'Vaccination service (Non-NHS)',
 'Vascular services',
 'Vascular surgery',
 'Visual impairment information and support',
 'Volleyball',
 'Walk-in COVID-19 vaccination service: ages 16 to 17 years',
 'Walk-in COVID-19 vaccination service: ages 18 to 64 years',
 'Walk-in COVID-19 vaccination service: ages 65 to 74 years',
 'Walk-in COVID-19 vaccination service: ages 75 or older',
 'Weight loss support groups',
 'Weight management (NHS)',
 'Weight management (paid-for)',
 'Weightlifting',
 'Wheelchair services',
 'Yoga',
 'Young carers services',
 "Young person's clinic",
 'Zumba'
"""



system_prompt_location = ""







system_prompt_article = '''Parse this article and convert it into JSON format, only giving the most concise information.
'''


system_prompt = '''You are an assistant that specialises in medical referral.
The will take in information given by another AI called Healthily, given in a JSON format.
The information includes the patient information, an article recommended by Healthily that summarises the patients most likely medical condition (but is not a diagnosis), 
and a list of services available that is located the closest to his location.
You should not repeat any information, give a very short summary on the medical condition, be nice and empathetic.
Less than 400 words.
The response will be in the format of a conversation.

'''

# Example JSON structures
dummy_userInfo = {
    "name": "John Doe",
    "age": 30,
    "email": "john.doe@example.com",
    "address": {
        "street": "248a Walkley Road",
        "city": "Sheffield",
        "country": "South Yorkshire",
        "postcode": "S62XN"
    }
}

dummy_articleURL = 'https://www.dev.livehealthily.com/health-library/conditions/scleroderma'

dummy_servicesJson = '''{
  "@odata.context": "https://nhsuksearchproduks.search.windows.net/indexes('syndicationprofiles-2-4-c-prod')/$metadata#docs(*)",
  "value": [
    {
      "@search.score": "1.7261853",
      "SearchKey": "X15",
      "ODSCode": "NY618",
      "OrganisationName": "Pain Management Solutions (Retford Primary Care Centre)",
      "OrganisationTypeId": "CLI",
      "OrganisationType": "Clinic",
      "OrganisationStatus": "Visible",
      "SummaryText": "<p><b>Retford Primary Care Centre is our main treatment site for the Bassetlaw area.</b>Pain Management Solutions offers a comprehensive pain service exclusively for NHS patients.</p>",
      "URL": "http://pmsltd.co.uk",
      "Address1": "North Road",
      "Address2": "null",
      "Address3": "null",
      "City": "Retford",
      "County": "Nottinghamshire",
      "Latitude": "53.3254508972168",
      "Longitude": "-0.9506186246871949",
      "Postcode": "DN22 7XF",
      "Geocode": "{\"type\":\"Point\",\"coordinates\":[-0.950619,53.3255],\"crs\":{\"type\":\"name\",\"properties\":{\"name\":\"EPSG:4326\"}}}",
      "OrganisationSubType": "Independent Sector",
      "OrganisationAliases": "[]",
      "ParentOrganisation": "{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"}",
      "Services": "[{\"ServiceName\":\"Pain Management\",\"ServiceCode\":\"SRV0076\",\"ServiceDescription\":\"null\",\"Contacts\":\"[]\",\"ServiceProvider\":{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"},\"Treatments\":\"[]\",\"OpeningTimes\":\"[]\",\"AgeRange\":\"[]\",\"Metrics\":\"[]\",\"KeyValueData\":\"[]\"}]",
      "OpeningTimes": "[]",
      "Contacts": "[{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Email\",\"ContactValue\":\"enquiries@pmsltd.co.uk\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Telephone\",\"ContactValue\":\"0800 0340406\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Website\",\"ContactValue\":\"http://pmsltd.co.uk\"}]",
      "Facilities": "[{\"Id\":\"28\",\"Name\":\"Car Parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Parking\"},{\"Id\":\"30\",\"Name\":\"Disabled parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Parking\"},{\"Id\":\"2\",\"Name\":\"Disabled parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"4\",\"Name\":\"Induction loop\",\"Value\":\"No\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"7\",\"Name\":\"Wheelchair access\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"31\",\"Name\":\"Access to TV\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"32\",\"Name\":\"Internet access\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"34\",\"Name\":\"Public telephone\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"21\",\"Name\":\"Translation services\",\"Value\":\"No\",\"FacilityGroupName\":\"Counselling and Support\"},{\"Id\":\"24\",\"Name\":\"Cafe\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Food and amenities on-site\"},{\"Id\":\"27\",\"Name\":\"Shop\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Food and amenities on-site\"}]",
      "Staff": "[]",
      "GSD": "null",
      "LastUpdatedDates": "{\"OpeningTimes\":\"null\",\"BankHolidayOpeningTimes\":\"null\",\"DentistsAcceptingPatients\":\"null\",\"Facilities\":\"2010-06-18T19:48:48.15Z\",\"HospitalDepartment\":\"null\",\"Services\":\"2010-06-18T19:48:48.15Z\",\"ContactDetails\":\"2010-06-18T19:48:48.15Z\",\"AcceptingPatients\":\"null\",\"KeyValueData\":\"[]\"}",
      "AcceptingPatients": "{\"GP\":\"null\",\"Dentist\":\"[]\"}",
      "GPRegistration": "null",
      "CCG": "null",
      "RelatedIAPTCCGs": "[]",
      "CCGLocalAuthority": "[]",
      "Trusts": "[]",
      "Metrics": "[{\"MetricID\":\"43\",\"MetricName\":\"Has Car Parking\",\"DisplayName\":\"Car parking\",\"Description\":\"Is there car parking at this organisation?\",\"Value\":\"yes\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Parking available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"yes\",\"BandingName\":\"Yes\"},{\"MetricID\":\"44\",\"MetricName\":\"Has Disabled Car Parking\",\"DisplayName\":\"Disabled parking\",\"Description\":\"Is disabled car parking available at this organisation?\",\"Value\":\"yes\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Disabled parking available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"yes\",\"BandingName\":\"Yes\"},{\"MetricID\":\"45\",\"MetricName\":\"Has Disabled Access\",\"DisplayName\":\"Disabled access\",\"Description\":\"Disabled access\",\"Value\":\"yes\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Disabled access available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"yes\",\"BandingName\":\"Yes\"},{\"MetricID\":\"46\",\"MetricName\":\"Has Translation Service\",\"DisplayName\":\"Translation services\",\"Description\":\"Translation services\",\"Value\":\"no\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Translation services not available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"no\",\"BandingName\":\"No\"},{\"MetricID\":\"47\",\"MetricName\":\"Has Induction Loop\",\"DisplayName\":\"Induction loop\",\"Description\":\"Induction loop in place\",\"Value\":\"no\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Does not have induction loop\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"no\",\"BandingName\":\"No\"},{\"MetricID\":\"99002\",\"MetricName\":\"Business Card: Has Car Parking\",\"DisplayName\":\"Car parking\",\"Description\":\"Is there car parking at this organisation?\",\"Value\":\"yes\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Parking available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"5\",\"MetricDisplayTypeName\":\"BandingImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"parking\",\"BandingName\":\"Yes\"}]"
    },
    {
      "@search.score": "1.676234",
      "SearchKey": "X226",
      "ODSCode": "NY621",
      "OrganisationName": "Pain Management Solutions (Harworth Primary Care Centre)",
      "OrganisationTypeId": "CLI",
      "OrganisationType": "Clinic",
      "OrganisationStatus": "Visible",
      "SummaryText": "<p><b>Harworth Primary Care Centre is a local outpatient site, treamtents are available from Retford Primary Care Centre</b>We are committed to developing pain management services that ensure the expertise of pain specialists is harnessed so that their maximum potential is more accessible to NHS patients.  We believe that pain management placed at the beginning of the patient journey supported by effective relationships between clinicians within and outside of the service, constitute the essential foundation required in order to achieve our vision.</p>",
      "URL": "www.pmsltd.co.uk",
      "Address1": "Scrooby Road",
      "Address2": "Harworth",
      "Address3": "",
      "City": "Doncaster",
      "County": "South Yorkshire",
      "Latitude": "53.41664123535156",
      "Longitude": "-1.069332480430603",
      "Postcode": "DN11 8JT",
      "Geocode": "{\"type\":\"Point\",\"coordinates\":[-1.06933,53.4166],\"crs\":{\"type\":\"name\",\"properties\":{\"name\":\"EPSG:4326\"}}}",
      "OrganisationSubType": "Independent Sector",
      "OrganisationAliases": "[]",
      "ParentOrganisation": "{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"}",
      "Services": "[{\"ServiceName\":\"Pain Management\",\"ServiceCode\":\"SRV0076\",\"ServiceDescription\":\"null\",\"Contacts\":\"[]\",\"ServiceProvider\":{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"},\"Treatments\":\"[]\",\"OpeningTimes\":\"[]\",\"AgeRange\":\"[]\",\"Metrics\":\"[]\",\"KeyValueData\":\"[]\"}]",
      "OpeningTimes": "[]",
      "Contacts": "[{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Email\",\"ContactValue\":\"enquiries@pmsltd.co.uk\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Telephone\",\"ContactValue\":\"0800 034 0406\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Website\",\"ContactValue\":\"www.pmsltd.co.uk\"}]",
      "Facilities": "[{\"Id\":\"2\",\"Name\":\"Disabled parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"4\",\"Name\":\"Induction loop\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"}]",
      "Staff": "[]",
      "GSD": "null",
      "LastUpdatedDates": "{\"OpeningTimes\":\"null\",\"BankHolidayOpeningTimes\":\"null\",\"DentistsAcceptingPatients\":\"null\",\"Facilities\":\"2010-06-18T19:48:48.15Z\",\"HospitalDepartment\":\"null\",\"Services\":\"2010-06-18T19:48:48.15Z\",\"ContactDetails\":\"2010-06-18T19:48:48.15Z\",\"AcceptingPatients\":\"null\",\"KeyValueData\":\"[]\"}",
      "AcceptingPatients": "{\"GP\":\"null\",\"Dentist\":\"[]\"}",
      "GPRegistration": "null",
      "CCG": "null",
      "RelatedIAPTCCGs": "[]",
      "CCGLocalAuthority": "[]",
      "Trusts": "[]",
      "Metrics": "[]"
    },
     "@odata.context": "https://nhsuksearchproduks.search.windows.net/indexes('syndicationprofiles-2-4-c-prod')/$metadata#docs(*)",
  "value": [
    {
      "@search.score": "1.7261853",
      "SearchKey": "X15",
      "ODSCode": "NY618",
      "OrganisationName": "Pain Management Solutions (Retford Primary Care Centre)",
      "OrganisationTypeId": "CLI",
      "OrganisationType": "Clinic",
      "OrganisationStatus": "Visible",
      "SummaryText": "<p><b>Retford Primary Care Centre is our main treatment site for the Bassetlaw area.</b>Pain Management Solutions offers a comprehensive pain service exclusively for NHS patients.</p>",
      "URL": "http://pmsltd.co.uk",
      "Address1": "North Road",
      "Address2": "null",
      "Address3": "null",
      "City": "Retford",
      "County": "Nottinghamshire",
      "Latitude": "53.3254508972168",
      "Longitude": "-0.9506186246871949",
      "Postcode": "DN22 7XF",
      "Geocode": "{\"type\":\"Point\",\"coordinates\":[-0.950619,53.3255],\"crs\":{\"type\":\"name\",\"properties\":{\"name\":\"EPSG:4326\"}}}",
      "OrganisationSubType": "Independent Sector",
      "OrganisationAliases": "[]",
      "ParentOrganisation": "{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"}",
      "Services": "[{\"ServiceName\":\"Pain Management\",\"ServiceCode\":\"SRV0076\",\"ServiceDescription\":\"null\",\"Contacts\":\"[]\",\"ServiceProvider\":{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"},\"Treatments\":\"[]\",\"OpeningTimes\":\"[]\",\"AgeRange\":\"[]\",\"Metrics\":\"[]\",\"KeyValueData\":\"[]\"}]",
      "OpeningTimes": "[]",
      "Contacts": "[{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Email\",\"ContactValue\":\"enquiries@pmsltd.co.uk\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Telephone\",\"ContactValue\":\"0800 0340406\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Website\",\"ContactValue\":\"http://pmsltd.co.uk\"}]",
      "Facilities": "[{\"Id\":\"28\",\"Name\":\"Car Parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Parking\"},{\"Id\":\"30\",\"Name\":\"Disabled parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Parking\"},{\"Id\":\"2\",\"Name\":\"Disabled parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"4\",\"Name\":\"Induction loop\",\"Value\":\"No\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"7\",\"Name\":\"Wheelchair access\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"31\",\"Name\":\"Access to TV\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"32\",\"Name\":\"Internet access\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"34\",\"Name\":\"Public telephone\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"21\",\"Name\":\"Translation services\",\"Value\":\"No\",\"FacilityGroupName\":\"Counselling and Support\"},{\"Id\":\"24\",\"Name\":\"Cafe\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Food and amenities on-site\"},{\"Id\":\"27\",\"Name\":\"Shop\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Food and amenities on-site\"}]",
      "Staff": "[]",
      "GSD": "null",
      "LastUpdatedDates": "{\"OpeningTimes\":\"null\",\"BankHolidayOpeningTimes\":\"null\",\"DentistsAcceptingPatients\":\"null\",\"Facilities\":\"2010-06-18T19:48:48.15Z\",\"HospitalDepartment\":\"null\",\"Services\":\"2010-06-18T19:48:48.15Z\",\"ContactDetails\":\"2010-06-18T19:48:48.15Z\",\"AcceptingPatients\":\"null\",\"KeyValueData\":\"[]\"}",
      "AcceptingPatients": "{\"GP\":\"null\",\"Dentist\":\"[]\"}",
      "GPRegistration": "null",
      "CCG": "null",
      "RelatedIAPTCCGs": "[]",
      "CCGLocalAuthority": "[]",
      "Trusts": "[]",
      "Metrics": "[{\"MetricID\":\"43\",\"MetricName\":\"Has Car Parking\",\"DisplayName\":\"Car parking\",\"Description\":\"Is there car parking at this organisation?\",\"Value\":\"yes\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Parking available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"yes\",\"BandingName\":\"Yes\"},{\"MetricID\":\"44\",\"MetricName\":\"Has Disabled Car Parking\",\"DisplayName\":\"Disabled parking\",\"Description\":\"Is disabled car parking available at this organisation?\",\"Value\":\"yes\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Disabled parking available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"yes\",\"BandingName\":\"Yes\"},{\"MetricID\":\"45\",\"MetricName\":\"Has Disabled Access\",\"DisplayName\":\"Disabled access\",\"Description\":\"Disabled access\",\"Value\":\"yes\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Disabled access available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"yes\",\"BandingName\":\"Yes\"},{\"MetricID\":\"46\",\"MetricName\":\"Has Translation Service\",\"DisplayName\":\"Translation services\",\"Description\":\"Translation services\",\"Value\":\"no\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Translation services not available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"no\",\"BandingName\":\"No\"},{\"MetricID\":\"47\",\"MetricName\":\"Has Induction Loop\",\"DisplayName\":\"Induction loop\",\"Description\":\"Induction loop in place\",\"Value\":\"no\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Does not have induction loop\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"4\",\"MetricDisplayTypeName\":\"BooleanImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"no\",\"BandingName\":\"No\"},{\"MetricID\":\"99002\",\"MetricName\":\"Business Card: Has Car Parking\",\"DisplayName\":\"Car parking\",\"Description\":\"Is there car parking at this organisation?\",\"Value\":\"yes\",\"Value2\":\"null\",\"Value3\":\"null\",\"Text\":\"Parking available\",\"LinkUrl\":\"null\",\"LinkText\":\"null\",\"MetricDisplayTypeID\":\"5\",\"MetricDisplayTypeName\":\"BandingImage\",\"HospitalSectorType\":\"null\",\"MetricText\":\"null\",\"DefaultText\":\"null\",\"IsMetaMetric\":\"true\",\"BandingClassification\":\"parking\",\"BandingName\":\"Yes\"}]"
    },
    {
      "@search.score": "1.676234",
      "SearchKey": "X226",
      "ODSCode": "NY621",
      "OrganisationName": "Pain Management Solutions (Harworth Primary Care Centre)",
      "OrganisationTypeId": "CLI",
      "OrganisationType": "Clinic",
      "OrganisationStatus": "Visible",
      "SummaryText": "<p><b>Harworth Primary Care Centre is a local outpatient site, treamtents are available from Retford Primary Care Centre</b>We are committed to developing pain management services that ensure the expertise of pain specialists is harnessed so that their maximum potential is more accessible to NHS patients.  We believe that pain management placed at the beginning of the patient journey supported by effective relationships between clinicians within and outside of the service, constitute the essential foundation required in order to achieve our vision.</p>",
      "URL": "www.pmsltd.co.uk",
      "Address1": "Scrooby Road",
      "Address2": "Harworth",
      "Address3": "",
      "City": "Doncaster",
      "County": "South Yorkshire",
      "Latitude": "53.41664123535156",
      "Longitude": "-1.069332480430603",
      "Postcode": "DN11 8JT",
      "Geocode": "{\"type\":\"Point\",\"coordinates\":[-1.06933,53.4166],\"crs\":{\"type\":\"name\",\"properties\":{\"name\":\"EPSG:4326\"}}}",
      "OrganisationSubType": "Independent Sector",
      "OrganisationAliases": "[]",
      "ParentOrganisation": "{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"}",
      "Services": "[{\"ServiceName\":\"Pain Management\",\"ServiceCode\":\"SRV0076\",\"ServiceDescription\":\"null\",\"Contacts\":\"[]\",\"ServiceProvider\":{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"},\"Treatments\":\"[]\",\"OpeningTimes\":\"[]\",\"AgeRange\":\"[]\",\"Metrics\":\"[]\",\"KeyValueData\":\"[]\"}]",
      "OpeningTimes": "[]",
      "Contacts": "[{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Email\",\"ContactValue\":\"enquiries@pmsltd.co.uk\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Telephone\",\"ContactValue\":\"0800 034 0406\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Website\",\"ContactValue\":\"www.pmsltd.co.uk\"}]",
      "Facilities": "[{\"Id\":\"2\",\"Name\":\"Disabled parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"4\",\"Name\":\"Induction loop\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"}]",
      "Staff": "[]",
      "GSD": "null",
      "LastUpdatedDates": "{\"OpeningTimes\":\"null\",\"BankHolidayOpeningTimes\":\"null\",\"DentistsAcceptingPatients\":\"null\",\"Facilities\":\"2010-06-18T19:48:48.15Z\",\"HospitalDepartment\":\"null\",\"Services\":\"2010-06-18T19:48:48.15Z\",\"ContactDetails\":\"2010-06-18T19:48:48.15Z\",\"AcceptingPatients\":\"null\",\"KeyValueData\":\"[]\"}",
      "AcceptingPatients": "{\"GP\":\"null\",\"Dentist\":\"[]\"}",
      "GPRegistration": "null",
      "CCG": "null",
      "RelatedIAPTCCGs": "[]",
      "CCGLocalAuthority": "[]",
      "Trusts": "[]",
      "Metrics": "[]"
    },
    {
      "@search.score": "1.676234",
      "SearchKey": "X227",
      "ODSCode": "NY622",
      "OrganisationName": "Pain Management Solutions (Retford Primary Care Centre)",
      "OrganisationTypeId": "CLI",
      "OrganisationType": "Clinic",
      "OrganisationStatus": "Visible",
      "SummaryText": "<p><b>Retford Primary Care Centre is our main treatment site for the Bassetlaw area.</b>Pain Management Solutions offers a comprehensive pain service exclusively for NHS patients.</p>",
      "URL": "http://pmsltd.co.uk",
      "Address1": "North Road",
      "Address2": "null",
      "Address3": "null",
      "City": "Sheffield",
      "County": "South Yorkshire",
      "Latitude": "53.3254508972168",
      "Longitude": "-0.9506186246871949",
      "Postcode": "S61JD",
      "Geocode": "{\"type\":\"Point\",\"coordinates\":[-0.950619,53.3255],\"crs\":{\"type\":\"name\",\"properties\":{\"name\":\"EPSG:4326\"}}}",
      "OrganisationSubType": "Independent Sector",
      "OrganisationAliases": "[]",
      "ParentOrganisation": "{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"}",
      "Services": "[{\"ServiceName\":\"Pain Management\",\"ServiceCode\":\"SRV0076\",\"ServiceDescription\":\"null\",\"Contacts\":\"[]\",\"ServiceProvider\":{\"ODSCode\":\"NY6\",\"OrganisationName\":\"Connect Health Pain Services\"},\"Treatments\":\"[]\",\"OpeningTimes\":\"[]\",\"AgeRange\":\"[]\",\"Metrics\":\"[]\",\"KeyValueData\":\"[]\"}]",
      "OpeningTimes": "[]",
      "Contacts": "[{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Email\",\"ContactValue\":\"enquiries@pmsltd.co.uk\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Telephone\",\"ContactValue\":\"0800 0340406\"},{\"ContactType\":\"Primary\",\"ContactAvailabilityType\":\"Office hours\",\"ContactMethodType\":\"Website\",\"ContactValue\":\"http://pmsltd.co.uk\"}]",
      "Facilities": "[{\"Id\":\"28\",\"Name\":\"Car Parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Parking\"},{\"Id\":\"30\",\"Name\":\"Disabled parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Parking\"},{\"Id\":\"2\",\"Name\":\"Disabled parking\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"4\",\"Name\":\"Induction loop\",\"Value\":\"No\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"7\",\"Name\":\"Wheelchair access\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Accessibility\"},{\"Id\":\"31\",\"Name\":\"Access to TV\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"32\",\"Name\":\"Internet access\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"34\",\"Name\":\"Public telephone\",\"Value\":\"No\",\"FacilityGroupName\":\"Communications\"},{\"Id\":\"21\",\"Name\":\"Translation services\",\"Value\":\"No\",\"FacilityGroupName\":\"Counselling and Support\"},{\"Id\":\"24\",\"Name\":\"Cafe\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Food and amenities on-site\"},{\"Id\":\"27\",\"Name\":\"Shop\",\"Value\":\"Yes\",\"FacilityGroupName\":\"Food and amenities on-site\"}]",
      "Staff": "[]",
      "GSD": "null",
      "LastUpdatedDates": "{\"OpeningTimes\":\"null\",\"BankHolidayOpeningTimes\":\"null\",\"DentistsAcceptingPatients\":\"null\",\"Facilities\":\"2010-06-18T19:48:48.15Z\",\"HospitalDepartment\":\"null\",\"Services\":\"2010-06-18T19:48:48.15Z\",\"ContactDetails\":\"2010-06-18T19:48:48.15Z\",\"AcceptingPatients\":\"null\",\"KeyValueData\":\"[]\"}",
      "AcceptingPatients": "{\"GP\":\"null\",\"Dentist\":\"[]\"}",
      "GPRegistration": "null",
      "CCG": "null",
      "RelatedIAPTCCGs": "[]",
      "CCGLocalAuthority": "[]",
      "Trusts": "[]",
      "Metrics": "[]"
    }
  ]
}'''

